[pytest]
testpaths = tests
addopts = --browser chromium --tracing retain-on-failure --screenshot only-on-failure --output reports/artifacts --junitxml reports/junit.xml --html reports/index.html --self-contained-html -v
